version: "3.9"
services:
  tdengine-1:
    image: tdengine/tdengine:3.0.5.0
    restart: unless-stopped
    ports:
      - 16030:6030
      - 16041:6041
    volumes:
      - tdengine1:/var/lib/taos
  tdengine-2:
    image: tdengine/tdengine:3.0.5.0
    restart: unless-stopped
    ports:
      - 26030:6030
      - 26041:6041
    volumes:
      - tdengine2:/var/lib/taos
volumes:
  tdengine1:
  tdengine2:
